//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.01 at 08:01:34 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tempuri.org/PurchaseOrderSchema.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.cjhndrx.trips.po_xml_classes;
